// <auto-generated />
using Backend.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Model.Todo.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = false,
                            Title = "delectus aut autem",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            Title = "quis ut nam facilis et officia qui",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Completed = false,
                            Title = "fugiat veniam minus",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Completed = true,
                            Title = "et porro tempora",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Completed = false,
                            Title = "laboriosam mollitia et enim quasi adipisci quia provident illum",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Completed = false,
                            Title = "qui ullam ratione quibusdam voluptatem quia omnis",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Completed = false,
                            Title = "illo expedita consequatur quia in",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Completed = true,
                            Title = "quo adipisci enim quam ut ab",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Completed = false,
                            Title = "molestiae perspiciatis ipsa",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Completed = true,
                            Title = "illo est ratione doloremque quia maiores aut",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Completed = true,
                            Title = "vero rerum temporibus dolor",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Completed = true,
                            Title = "ipsa repellendus fugit nisi",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Completed = false,
                            Title = "et doloremque nulla",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Completed = true,
                            Title = "repellendus sunt dolores architecto voluptatum",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Completed = true,
                            Title = "ab voluptatum amet voluptas",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Completed = true,
                            Title = "accusamus eos facilis sint et aut voluptatem",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            Completed = true,
                            Title = "quo laboriosam deleniti aut qui",
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            Completed = false,
                            Title = "dolorum est consequatur ea mollitia in culpa",
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Completed = true,
                            Title = "molestiae ipsa aut voluptatibus pariatur dolor nihil",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Completed = true,
                            Title = "ullam nobis libero sapiente ad optio sint",
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Completed = false,
                            Title = "suscipit repellat esse quibusdam voluptatem incidunt",
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            Completed = true,
                            Title = "distinctio vitae autem nihil ut molestias quo",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            Completed = false,
                            Title = "et itaque necessitatibus maxime molestiae qui quas velit",
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            Completed = false,
                            Title = "adipisci non ad dicta qui amet quaerat doloribus ea",
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Completed = true,
                            Title = "voluptas quo tenetur perspiciatis explicabo natus",
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            Completed = true,
                            Title = "aliquam aut quasi",
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            Completed = true,
                            Title = "veritatis pariatur delectus",
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            Completed = false,
                            Title = "nesciunt totam sit blanditiis sit",
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            Completed = false,
                            Title = "laborum aut in quam",
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            Completed = true,
                            Title = "nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis",
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            Completed = false,
                            Title = "repudiandae totam in est sint facere fuga",
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            Completed = false,
                            Title = "earum doloribus ea doloremque quis",
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            Completed = false,
                            Title = "sint sit aut vero",
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            Completed = false,
                            Title = "porro aut necessitatibus eaque distinctio",
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            Completed = true,
                            Title = "repellendus veritatis molestias dicta incidunt",
                            UserId = 2
                        },
                        new
                        {
                            Id = 36,
                            Completed = true,
                            Title = "excepturi deleniti adipisci voluptatem et neque optio illum ad",
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            Completed = false,
                            Title = "sunt cum tempora",
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            Completed = false,
                            Title = "totam quia non",
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            Completed = false,
                            Title = "doloremque quibusdam asperiores libero corrupti illum qui omnis",
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            Completed = true,
                            Title = "totam atque quo nesciunt",
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            Completed = false,
                            Title = "aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit",
                            UserId = 3
                        },
                        new
                        {
                            Id = 42,
                            Completed = false,
                            Title = "rerum perferendis error quia ut eveniet",
                            UserId = 3
                        },
                        new
                        {
                            Id = 43,
                            Completed = true,
                            Title = "tempore ut sint quis recusandae",
                            UserId = 3
                        },
                        new
                        {
                            Id = 44,
                            Completed = true,
                            Title = "cum debitis quis accusamus doloremque ipsa natus sapiente omnis",
                            UserId = 3
                        },
                        new
                        {
                            Id = 45,
                            Completed = false,
                            Title = "velit soluta adipisci molestias reiciendis harum",
                            UserId = 3
                        },
                        new
                        {
                            Id = 46,
                            Completed = false,
                            Title = "vel voluptatem repellat nihil placeat corporis",
                            UserId = 3
                        },
                        new
                        {
                            Id = 47,
                            Completed = false,
                            Title = "nam qui rerum fugiat accusamus",
                            UserId = 3
                        },
                        new
                        {
                            Id = 48,
                            Completed = false,
                            Title = "sit reprehenderit omnis quia",
                            UserId = 3
                        },
                        new
                        {
                            Id = 49,
                            Completed = false,
                            Title = "ut necessitatibus aut maiores debitis officia blanditiis velit et",
                            UserId = 3
                        },
                        new
                        {
                            Id = 50,
                            Completed = true,
                            Title = "cupiditate necessitatibus ullam aut quis dolor voluptate",
                            UserId = 3
                        },
                        new
                        {
                            Id = 51,
                            Completed = false,
                            Title = "distinctio exercitationem ab doloribus",
                            UserId = 3
                        },
                        new
                        {
                            Id = 52,
                            Completed = false,
                            Title = "nesciunt dolorum quis recusandae ad pariatur ratione",
                            UserId = 3
                        },
                        new
                        {
                            Id = 53,
                            Completed = false,
                            Title = "qui labore est occaecati recusandae aliquid quam",
                            UserId = 3
                        },
                        new
                        {
                            Id = 54,
                            Completed = true,
                            Title = "quis et est ut voluptate quam dolor",
                            UserId = 3
                        },
                        new
                        {
                            Id = 55,
                            Completed = true,
                            Title = "voluptatum omnis minima qui occaecati provident nulla voluptatem ratione",
                            UserId = 3
                        },
                        new
                        {
                            Id = 56,
                            Completed = true,
                            Title = "deleniti ea temporibus enim",
                            UserId = 3
                        },
                        new
                        {
                            Id = 57,
                            Completed = false,
                            Title = "pariatur et magnam ea doloribus similique voluptatem rerum quia",
                            UserId = 3
                        },
                        new
                        {
                            Id = 58,
                            Completed = false,
                            Title = "est dicta totam qui explicabo doloribus qui dignissimos",
                            UserId = 3
                        },
                        new
                        {
                            Id = 59,
                            Completed = false,
                            Title = "perspiciatis velit id laborum placeat iusto et aliquam odio",
                            UserId = 3
                        },
                        new
                        {
                            Id = 60,
                            Completed = true,
                            Title = "et sequi qui architecto ut adipisci",
                            UserId = 3
                        },
                        new
                        {
                            Id = 61,
                            Completed = true,
                            Title = "odit optio omnis qui sunt",
                            UserId = 4
                        },
                        new
                        {
                            Id = 62,
                            Completed = false,
                            Title = "et placeat et tempore aspernatur sint numquam",
                            UserId = 4
                        },
                        new
                        {
                            Id = 63,
                            Completed = true,
                            Title = "doloremque aut dolores quidem fuga qui nulla",
                            UserId = 4
                        },
                        new
                        {
                            Id = 64,
                            Completed = false,
                            Title = "voluptas consequatur qui ut quia magnam nemo esse",
                            UserId = 4
                        },
                        new
                        {
                            Id = 65,
                            Completed = false,
                            Title = "fugiat pariatur ratione ut asperiores necessitatibus magni",
                            UserId = 4
                        },
                        new
                        {
                            Id = 66,
                            Completed = false,
                            Title = "rerum eum molestias autem voluptatum sit optio",
                            UserId = 4
                        },
                        new
                        {
                            Id = 67,
                            Completed = false,
                            Title = "quia voluptatibus voluptatem quos similique maiores repellat",
                            UserId = 4
                        },
                        new
                        {
                            Id = 68,
                            Completed = false,
                            Title = "aut id perspiciatis voluptatem iusto",
                            UserId = 4
                        },
                        new
                        {
                            Id = 69,
                            Completed = false,
                            Title = "doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit",
                            UserId = 4
                        },
                        new
                        {
                            Id = 70,
                            Completed = false,
                            Title = "ut sequi accusantium et mollitia delectus sunt",
                            UserId = 4
                        },
                        new
                        {
                            Id = 71,
                            Completed = false,
                            Title = "aut velit saepe ullam",
                            UserId = 4
                        },
                        new
                        {
                            Id = 72,
                            Completed = false,
                            Title = "praesentium facilis facere quis harum voluptatibus voluptatem eum",
                            UserId = 4
                        },
                        new
                        {
                            Id = 73,
                            Completed = true,
                            Title = "sint amet quia totam corporis qui exercitationem commodi",
                            UserId = 4
                        },
                        new
                        {
                            Id = 74,
                            Completed = false,
                            Title = "expedita tempore nobis eveniet laborum maiores",
                            UserId = 4
                        },
                        new
                        {
                            Id = 75,
                            Completed = false,
                            Title = "occaecati adipisci est possimus totam",
                            UserId = 4
                        },
                        new
                        {
                            Id = 76,
                            Completed = true,
                            Title = "sequi dolorem sed",
                            UserId = 4
                        },
                        new
                        {
                            Id = 77,
                            Completed = false,
                            Title = "maiores aut nesciunt delectus exercitationem vel assumenda eligendi at",
                            UserId = 4
                        },
                        new
                        {
                            Id = 78,
                            Completed = false,
                            Title = "reiciendis est magnam amet nemo iste recusandae impedit quaerat",
                            UserId = 4
                        },
                        new
                        {
                            Id = 79,
                            Completed = true,
                            Title = "eum ipsa maxime ut",
                            UserId = 4
                        },
                        new
                        {
                            Id = 80,
                            Completed = true,
                            Title = "tempore molestias dolores rerum sequi voluptates ipsum consequatur",
                            UserId = 4
                        },
                        new
                        {
                            Id = 81,
                            Completed = true,
                            Title = "suscipit qui totam",
                            UserId = 5
                        },
                        new
                        {
                            Id = 82,
                            Completed = false,
                            Title = "voluptates eum voluptas et dicta",
                            UserId = 5
                        },
                        new
                        {
                            Id = 83,
                            Completed = true,
                            Title = "quidem at rerum quis ex aut sit quam",
                            UserId = 5
                        },
                        new
                        {
                            Id = 84,
                            Completed = false,
                            Title = "sunt veritatis ut voluptate",
                            UserId = 5
                        },
                        new
                        {
                            Id = 85,
                            Completed = true,
                            Title = "et quia ad iste a",
                            UserId = 5
                        },
                        new
                        {
                            Id = 86,
                            Completed = true,
                            Title = "incidunt ut saepe autem",
                            UserId = 5
                        },
                        new
                        {
                            Id = 87,
                            Completed = true,
                            Title = "laudantium quae eligendi consequatur quia et vero autem",
                            UserId = 5
                        },
                        new
                        {
                            Id = 88,
                            Completed = false,
                            Title = "vitae aut excepturi laboriosam sint aliquam et et accusantium",
                            UserId = 5
                        },
                        new
                        {
                            Id = 89,
                            Completed = true,
                            Title = "sequi ut omnis et",
                            UserId = 5
                        },
                        new
                        {
                            Id = 90,
                            Completed = true,
                            Title = "molestiae nisi accusantium tenetur dolorem et",
                            UserId = 5
                        },
                        new
                        {
                            Id = 91,
                            Completed = true,
                            Title = "nulla quis consequatur saepe qui id expedita",
                            UserId = 5
                        },
                        new
                        {
                            Id = 92,
                            Completed = true,
                            Title = "in omnis laboriosam",
                            UserId = 5
                        },
                        new
                        {
                            Id = 93,
                            Completed = true,
                            Title = "odio iure consequatur molestiae quibusdam necessitatibus quia sint",
                            UserId = 5
                        },
                        new
                        {
                            Id = 94,
                            Completed = false,
                            Title = "facilis modi saepe mollitia",
                            UserId = 5
                        },
                        new
                        {
                            Id = 95,
                            Completed = true,
                            Title = "vel nihil et molestiae iusto assumenda nemo quo ut",
                            UserId = 5
                        },
                        new
                        {
                            Id = 96,
                            Completed = false,
                            Title = "nobis suscipit ducimus enim asperiores voluptas",
                            UserId = 5
                        },
                        new
                        {
                            Id = 97,
                            Completed = false,
                            Title = "dolorum laboriosam eos qui iure aliquam",
                            UserId = 5
                        },
                        new
                        {
                            Id = 98,
                            Completed = true,
                            Title = "debitis accusantium ut quo facilis nihil quis sapiente necessitatibus",
                            UserId = 5
                        },
                        new
                        {
                            Id = 99,
                            Completed = false,
                            Title = "neque voluptates ratione",
                            UserId = 5
                        },
                        new
                        {
                            Id = 100,
                            Completed = false,
                            Title = "excepturi a et neque qui expedita vel voluptate",
                            UserId = 5
                        },
                        new
                        {
                            Id = 101,
                            Completed = false,
                            Title = "explicabo enim cumque porro aperiam occaecati minima",
                            UserId = 6
                        },
                        new
                        {
                            Id = 102,
                            Completed = false,
                            Title = "sed ab consequatur",
                            UserId = 6
                        },
                        new
                        {
                            Id = 103,
                            Completed = false,
                            Title = "non sunt delectus illo nulla tenetur enim omnis",
                            UserId = 6
                        },
                        new
                        {
                            Id = 104,
                            Completed = false,
                            Title = "excepturi non laudantium quo",
                            UserId = 6
                        },
                        new
                        {
                            Id = 105,
                            Completed = true,
                            Title = "totam quia dolorem et illum repellat voluptas optio",
                            UserId = 6
                        },
                        new
                        {
                            Id = 106,
                            Completed = true,
                            Title = "ad illo quis voluptatem temporibus",
                            UserId = 6
                        },
                        new
                        {
                            Id = 107,
                            Completed = false,
                            Title = "praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt",
                            UserId = 6
                        },
                        new
                        {
                            Id = 108,
                            Completed = true,
                            Title = "a eos eaque nihil et exercitationem incidunt delectus",
                            UserId = 6
                        },
                        new
                        {
                            Id = 109,
                            Completed = true,
                            Title = "autem temporibus harum quisquam in culpa",
                            UserId = 6
                        },
                        new
                        {
                            Id = 110,
                            Completed = true,
                            Title = "aut aut ea corporis",
                            UserId = 6
                        },
                        new
                        {
                            Id = 111,
                            Completed = false,
                            Title = "magni accusantium labore et id quis provident",
                            UserId = 6
                        },
                        new
                        {
                            Id = 112,
                            Completed = false,
                            Title = "consectetur impedit quisquam qui deserunt non rerum consequuntur eius",
                            UserId = 6
                        },
                        new
                        {
                            Id = 113,
                            Completed = false,
                            Title = "quia atque aliquam sunt impedit voluptatum rerum assumenda nisi",
                            UserId = 6
                        },
                        new
                        {
                            Id = 114,
                            Completed = false,
                            Title = "cupiditate quos possimus corporis quisquam exercitationem beatae",
                            UserId = 6
                        },
                        new
                        {
                            Id = 115,
                            Completed = false,
                            Title = "sed et ea eum",
                            UserId = 6
                        },
                        new
                        {
                            Id = 116,
                            Completed = true,
                            Title = "ipsa dolores vel facilis ut",
                            UserId = 6
                        },
                        new
                        {
                            Id = 117,
                            Completed = false,
                            Title = "sequi quae est et qui qui eveniet asperiores",
                            UserId = 6
                        },
                        new
                        {
                            Id = 118,
                            Completed = false,
                            Title = "quia modi consequatur vero fugiat",
                            UserId = 6
                        },
                        new
                        {
                            Id = 119,
                            Completed = false,
                            Title = "corporis ducimus ea perspiciatis iste",
                            UserId = 6
                        },
                        new
                        {
                            Id = 120,
                            Completed = false,
                            Title = "dolorem laboriosam vel voluptas et aliquam quasi",
                            UserId = 6
                        },
                        new
                        {
                            Id = 121,
                            Completed = true,
                            Title = "inventore aut nihil minima laudantium hic qui omnis",
                            UserId = 7
                        },
                        new
                        {
                            Id = 122,
                            Completed = true,
                            Title = "provident aut nobis culpa",
                            UserId = 7
                        },
                        new
                        {
                            Id = 123,
                            Completed = false,
                            Title = "esse et quis iste est earum aut impedit",
                            UserId = 7
                        },
                        new
                        {
                            Id = 124,
                            Completed = false,
                            Title = "qui consectetur id",
                            UserId = 7
                        },
                        new
                        {
                            Id = 125,
                            Completed = false,
                            Title = "aut quasi autem iste tempore illum possimus",
                            UserId = 7
                        },
                        new
                        {
                            Id = 126,
                            Completed = true,
                            Title = "ut asperiores perspiciatis veniam ipsum rerum saepe",
                            UserId = 7
                        },
                        new
                        {
                            Id = 127,
                            Completed = true,
                            Title = "voluptatem libero consectetur rerum ut",
                            UserId = 7
                        },
                        new
                        {
                            Id = 128,
                            Completed = false,
                            Title = "eius omnis est qui voluptatem autem",
                            UserId = 7
                        },
                        new
                        {
                            Id = 129,
                            Completed = false,
                            Title = "rerum culpa quis harum",
                            UserId = 7
                        },
                        new
                        {
                            Id = 130,
                            Completed = true,
                            Title = "nulla aliquid eveniet harum laborum libero alias ut unde",
                            UserId = 7
                        },
                        new
                        {
                            Id = 131,
                            Completed = false,
                            Title = "qui ea incidunt quis",
                            UserId = 7
                        },
                        new
                        {
                            Id = 132,
                            Completed = true,
                            Title = "qui molestiae voluptatibus velit iure harum quisquam",
                            UserId = 7
                        },
                        new
                        {
                            Id = 133,
                            Completed = true,
                            Title = "et labore eos enim rerum consequatur sunt",
                            UserId = 7
                        },
                        new
                        {
                            Id = 134,
                            Completed = false,
                            Title = "molestiae doloribus et laborum quod ea",
                            UserId = 7
                        },
                        new
                        {
                            Id = 135,
                            Completed = false,
                            Title = "facere ipsa nam eum voluptates reiciendis vero qui",
                            UserId = 7
                        },
                        new
                        {
                            Id = 136,
                            Completed = false,
                            Title = "asperiores illo tempora fuga sed ut quasi adipisci",
                            UserId = 7
                        },
                        new
                        {
                            Id = 137,
                            Completed = false,
                            Title = "qui sit non",
                            UserId = 7
                        },
                        new
                        {
                            Id = 138,
                            Completed = true,
                            Title = "placeat minima consequatur rem qui ut",
                            UserId = 7
                        },
                        new
                        {
                            Id = 139,
                            Completed = false,
                            Title = "consequatur doloribus id possimus voluptas a voluptatem",
                            UserId = 7
                        },
                        new
                        {
                            Id = 140,
                            Completed = true,
                            Title = "aut consectetur in blanditiis deserunt quia sed laboriosam",
                            UserId = 7
                        },
                        new
                        {
                            Id = 141,
                            Completed = true,
                            Title = "explicabo consectetur debitis voluptates quas quae culpa rerum non",
                            UserId = 8
                        },
                        new
                        {
                            Id = 142,
                            Completed = true,
                            Title = "maiores accusantium architecto necessitatibus reiciendis ea aut",
                            UserId = 8
                        },
                        new
                        {
                            Id = 143,
                            Completed = false,
                            Title = "eum non recusandae cupiditate animi",
                            UserId = 8
                        },
                        new
                        {
                            Id = 144,
                            Completed = false,
                            Title = "ut eum exercitationem sint",
                            UserId = 8
                        },
                        new
                        {
                            Id = 145,
                            Completed = false,
                            Title = "beatae qui ullam incidunt voluptatem non nisi aliquam",
                            UserId = 8
                        },
                        new
                        {
                            Id = 146,
                            Completed = true,
                            Title = "molestiae suscipit ratione nihil odio libero impedit vero totam",
                            UserId = 8
                        },
                        new
                        {
                            Id = 147,
                            Completed = true,
                            Title = "eum itaque quod reprehenderit et facilis dolor autem ut",
                            UserId = 8
                        },
                        new
                        {
                            Id = 148,
                            Completed = false,
                            Title = "esse quas et quo quasi exercitationem",
                            UserId = 8
                        },
                        new
                        {
                            Id = 149,
                            Completed = false,
                            Title = "animi voluptas quod perferendis est",
                            UserId = 8
                        },
                        new
                        {
                            Id = 150,
                            Completed = false,
                            Title = "eos amet tempore laudantium fugit a",
                            UserId = 8
                        },
                        new
                        {
                            Id = 151,
                            Completed = true,
                            Title = "accusamus adipisci dicta qui quo ea explicabo sed vero",
                            UserId = 8
                        },
                        new
                        {
                            Id = 152,
                            Completed = false,
                            Title = "odit eligendi recusandae doloremque cumque non",
                            UserId = 8
                        },
                        new
                        {
                            Id = 153,
                            Completed = false,
                            Title = "ea aperiam consequatur qui repellat eos",
                            UserId = 8
                        },
                        new
                        {
                            Id = 154,
                            Completed = true,
                            Title = "rerum non ex sapiente",
                            UserId = 8
                        },
                        new
                        {
                            Id = 155,
                            Completed = true,
                            Title = "voluptatem nobis consequatur et assumenda magnam",
                            UserId = 8
                        },
                        new
                        {
                            Id = 156,
                            Completed = true,
                            Title = "nam quia quia nulla repellat assumenda quibusdam sit nobis",
                            UserId = 8
                        },
                        new
                        {
                            Id = 157,
                            Completed = true,
                            Title = "dolorem veniam quisquam deserunt repellendus",
                            UserId = 8
                        },
                        new
                        {
                            Id = 158,
                            Completed = true,
                            Title = "debitis vitae delectus et harum accusamus aut deleniti a",
                            UserId = 8
                        },
                        new
                        {
                            Id = 159,
                            Completed = true,
                            Title = "debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis",
                            UserId = 8
                        },
                        new
                        {
                            Id = 160,
                            Completed = false,
                            Title = "et praesentium aliquam est",
                            UserId = 8
                        },
                        new
                        {
                            Id = 161,
                            Completed = true,
                            Title = "ex hic consequuntur earum omnis alias ut occaecati culpa",
                            UserId = 9
                        },
                        new
                        {
                            Id = 162,
                            Completed = true,
                            Title = "omnis laboriosam molestias animi sunt dolore",
                            UserId = 9
                        },
                        new
                        {
                            Id = 163,
                            Completed = false,
                            Title = "natus corrupti maxime laudantium et voluptatem laboriosam odit",
                            UserId = 9
                        },
                        new
                        {
                            Id = 164,
                            Completed = false,
                            Title = "reprehenderit quos aut aut consequatur est sed",
                            UserId = 9
                        },
                        new
                        {
                            Id = 165,
                            Completed = false,
                            Title = "fugiat perferendis sed aut quidem",
                            UserId = 9
                        },
                        new
                        {
                            Id = 166,
                            Completed = false,
                            Title = "quos quo possimus suscipit minima ut",
                            UserId = 9
                        },
                        new
                        {
                            Id = 167,
                            Completed = false,
                            Title = "et quis minus quo a asperiores molestiae",
                            UserId = 9
                        },
                        new
                        {
                            Id = 168,
                            Completed = false,
                            Title = "recusandae quia qui sunt libero",
                            UserId = 9
                        },
                        new
                        {
                            Id = 169,
                            Completed = true,
                            Title = "ea odio perferendis officiis",
                            UserId = 9
                        },
                        new
                        {
                            Id = 170,
                            Completed = false,
                            Title = "quisquam aliquam quia doloribus aut",
                            UserId = 9
                        },
                        new
                        {
                            Id = 171,
                            Completed = true,
                            Title = "fugiat aut voluptatibus corrupti deleniti velit iste odio",
                            UserId = 9
                        },
                        new
                        {
                            Id = 172,
                            Completed = false,
                            Title = "et provident amet rerum consectetur et voluptatum",
                            UserId = 9
                        },
                        new
                        {
                            Id = 173,
                            Completed = false,
                            Title = "harum ad aperiam quis",
                            UserId = 9
                        },
                        new
                        {
                            Id = 174,
                            Completed = false,
                            Title = "similique aut quo",
                            UserId = 9
                        },
                        new
                        {
                            Id = 175,
                            Completed = true,
                            Title = "laudantium eius officia perferendis provident perspiciatis asperiores",
                            UserId = 9
                        },
                        new
                        {
                            Id = 176,
                            Completed = false,
                            Title = "magni soluta corrupti ut maiores rem quidem",
                            UserId = 9
                        },
                        new
                        {
                            Id = 177,
                            Completed = false,
                            Title = "et placeat temporibus voluptas est tempora quos quibusdam",
                            UserId = 9
                        },
                        new
                        {
                            Id = 178,
                            Completed = true,
                            Title = "nesciunt itaque commodi tempore",
                            UserId = 9
                        },
                        new
                        {
                            Id = 179,
                            Completed = true,
                            Title = "omnis consequuntur cupiditate impedit itaque ipsam quo",
                            UserId = 9
                        },
                        new
                        {
                            Id = 180,
                            Completed = true,
                            Title = "debitis nisi et dolorem repellat et",
                            UserId = 9
                        },
                        new
                        {
                            Id = 181,
                            Completed = false,
                            Title = "ut cupiditate sequi aliquam fuga maiores",
                            UserId = 10
                        },
                        new
                        {
                            Id = 182,
                            Completed = true,
                            Title = "inventore saepe cumque et aut illum enim",
                            UserId = 10
                        },
                        new
                        {
                            Id = 183,
                            Completed = true,
                            Title = "omnis nulla eum aliquam distinctio",
                            UserId = 10
                        },
                        new
                        {
                            Id = 184,
                            Completed = false,
                            Title = "molestias modi perferendis perspiciatis",
                            UserId = 10
                        },
                        new
                        {
                            Id = 185,
                            Completed = false,
                            Title = "voluptates dignissimos sed doloribus animi quaerat aut",
                            UserId = 10
                        },
                        new
                        {
                            Id = 186,
                            Completed = false,
                            Title = "explicabo odio est et",
                            UserId = 10
                        },
                        new
                        {
                            Id = 187,
                            Completed = false,
                            Title = "consequuntur animi possimus",
                            UserId = 10
                        },
                        new
                        {
                            Id = 188,
                            Completed = true,
                            Title = "vel non beatae est",
                            UserId = 10
                        },
                        new
                        {
                            Id = 189,
                            Completed = true,
                            Title = "culpa eius et voluptatem et",
                            UserId = 10
                        },
                        new
                        {
                            Id = 190,
                            Completed = true,
                            Title = "accusamus sint iusto et voluptatem exercitationem",
                            UserId = 10
                        },
                        new
                        {
                            Id = 191,
                            Completed = true,
                            Title = "temporibus atque distinctio omnis eius impedit tempore molestias pariatur",
                            UserId = 10
                        },
                        new
                        {
                            Id = 192,
                            Completed = false,
                            Title = "ut quas possimus exercitationem sint voluptates",
                            UserId = 10
                        },
                        new
                        {
                            Id = 193,
                            Completed = true,
                            Title = "rerum debitis voluptatem qui eveniet tempora distinctio a",
                            UserId = 10
                        },
                        new
                        {
                            Id = 194,
                            Completed = false,
                            Title = "sed ut vero sit molestiae",
                            UserId = 10
                        },
                        new
                        {
                            Id = 195,
                            Completed = true,
                            Title = "rerum ex veniam mollitia voluptatibus pariatur",
                            UserId = 10
                        },
                        new
                        {
                            Id = 196,
                            Completed = true,
                            Title = "consequuntur aut ut fugit similique",
                            UserId = 10
                        },
                        new
                        {
                            Id = 197,
                            Completed = true,
                            Title = "dignissimos quo nobis earum saepe",
                            UserId = 10
                        },
                        new
                        {
                            Id = 198,
                            Completed = true,
                            Title = "quis eius est sint explicabo",
                            UserId = 10
                        },
                        new
                        {
                            Id = 199,
                            Completed = true,
                            Title = "numquam repellendus a magnam",
                            UserId = 10
                        },
                        new
                        {
                            Id = 200,
                            Completed = false,
                            Title = "ipsam aperiam voluptates qui",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Backend.Model.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "website");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Sincere@april.biz",
                            Name = "Leanne Graham",
                            Password = "asd123",
                            Username = "Bret",
                            Website = "hildegard.org"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Shanna@melissa.tv",
                            Name = "Ervin Howell",
                            Password = "asd123",
                            Username = "Antonette",
                            Website = "anastasia.net"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Nathan@yesenia.net",
                            Name = "Clementine Bauch",
                            Password = "asd123",
                            Username = "Samantha",
                            Website = "ramiro.info"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Julianne.OConner@kory.org",
                            Name = "Patricia Lebsack",
                            Password = "asd123",
                            Username = "Karianne",
                            Website = "kale.biz"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Lucio_Hettinger@annie.ca",
                            Name = "Chelsey Dietrich",
                            Password = "asd123",
                            Username = "Kamren",
                            Website = "demarco.info"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Karley_Dach@jasper.info",
                            Name = "Mrs. Dennis Schulist",
                            Password = "asd123",
                            Username = "Leopoldo_Corkery",
                            Website = "ola.org"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Telly.Hoeger@billy.biz",
                            Name = "Kurtis Weissnat",
                            Password = "asd123",
                            Username = "Elwyn.Skiles",
                            Website = "elvis.io"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Sherwood@rosamond.me",
                            Name = "Nicholas Runolfsdottir V",
                            Password = "asd123",
                            Username = "Maxime_Nienow",
                            Website = "jacynthe.com"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Chaim_McDermott@dana.io",
                            Name = "Glenna Reichert",
                            Password = "asd123",
                            Username = "Delphine",
                            Website = "conrad.com"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Rey.Padberg@karina.biz",
                            Name = "Clementina DuBuque",
                            Password = "asd123",
                            Username = "Moriah.Stanton",
                            Website = "ambrose.net"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
